package map;
// Generated Sep 1, 2013 9:33:25 AM by Hibernate Tools 3.2.1.GA



/**
 * SchoolId generated by hbm2java
 */
public class SchoolId  implements java.io.Serializable {


     private int idschool;
     private int subjectIdsubject;

    public SchoolId() {
    }

    public SchoolId(int idschool, int subjectIdsubject) {
       this.idschool = idschool;
       this.subjectIdsubject = subjectIdsubject;
    }
   
    public int getIdschool() {
        return this.idschool;
    }
    
    public void setIdschool(int idschool) {
        this.idschool = idschool;
    }
    public int getSubjectIdsubject() {
        return this.subjectIdsubject;
    }
    
    public void setSubjectIdsubject(int subjectIdsubject) {
        this.subjectIdsubject = subjectIdsubject;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SchoolId) ) return false;
		 SchoolId castOther = ( SchoolId ) other; 
         
		 return (this.getIdschool()==castOther.getIdschool())
 && (this.getSubjectIdsubject()==castOther.getSubjectIdsubject());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdschool();
         result = 37 * result + this.getSubjectIdsubject();
         return result;
   }   


}


